=== MateuSai/Where-is-the-Princess/Rooms/Biomes/biome_conf_schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "title": "Biome Configuration",
    "description": "Configuration for a biome",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "day_night_cycle": {
            "type": "boolean"
        },
        "background_color": {
            "type": "string"
        },
        "light_color": {
            "type": "string"
        },
        "corridor_atlas_id": {
            "type": "integer"
        },
        "room_atlas_id": {
            "type": "integer"
        },
        "room_rect_margin": {
            "type": "integer"
        },
        "max_corridor_length": {
            "type": "integer"
        },
        "restart_generation_if_extra_connections_exceed_max_corridor_length": {
            "type": "boolean"
        },
        "extra_connections": {
            "type": "number",
            "minimum": 0
        },
        "minimap_texture": {
            "type": "string"
        },
        "vertical_door_texture": {
            "type": "string"
        },
        "horizontal_down_door_texture": {
            "type": "string"
        },
        "horizontal_up_door_texture": {
            "type": "string"
        },
        "vertical_corridor_symmetric_lights": {
            "type": "boolean"
        },
        "corridor_floor_tiles_coor": {
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "integer"
                },
                "minItems": 2,
                "maxItems": 2
            },
            "uniqueItems": true
        },
        "default_num_combat_rooms": {
            "type": "integer",
            "minimum": 0
        },
        "default_num_chest_rooms": {
            "type": "integer",
            "minimum": 0
        },
        "default_num_special_rooms": {
            "type": "integer",
            "minimum": 0
        },
        "default_weapons_on_floor": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        },
        "default_num_weapons_on_floor_per_tile": {
            "type": "integer",
            "minimum": 0
        },
        "levels": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "$ref": "./level_schema.json"
            }
        },
        "music": {
            "type": "string"
        },
        "music_volume_db": {
            "type": "number"
        },
        "encyclopedia_background": {
            "type": "string"
        },
        "weather_modificators": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        },
        "temperature": {
            "type": "number"
        }
    },
    "required": [
        "minimap_texture",
        "encyclopedia_background"
    ]
}

=== MateuSai/Where-is-the-Princess/Rooms/Biomes/forest/conf.json
{
	"$schema": "../../../Rooms/Biomes/biome_conf_schema.json",
	"name": "FOREST",
	"day_night_cycle": true,
	"background_color": "1a1c00",
	"light_color": "878787",
	"corridor_atlas_id": 0,
	"room_atlas_id": 0,
	"extra_connections": 0.5,
	"minimap_texture": "res://Art/16x16 Pixel Art Roguelike (Forest) Pack/tilesets/triple tilemap forest_minimap_sepia.png",
	"vertical_door_texture": "res://Art/16x16 Pixel Art Roguelike (Forest) Pack/doors/forest_vertical_door_canvas_texture.tres",
	"horizontal_down_door_texture": "res://Art/16x16 Pixel Art Roguelike (Forest) Pack/doors/forest_horizontal_door_canvas_texture.tres",
	"horizontal_up_door_texture": "res://Art/16x16 Pixel Art Roguelike (Forest) Pack/doors/forest_horizontal_door_canvas_texture.tres",
	"vertical_corridor_symmetric_lights": false,
	"corridor_floor_tiles_coor": [
		[
			5,
			2
		],
		[
			5,
			3
		],
		[
			7,
			2
		],
		[
			7,
			3
		]
	],
	"default_num_combat_rooms": 5,
	"default_num_special_rooms": 1,
	"default_weapons_on_floor": [
		"res://Weapons/Melee/branch/branch.tscn",
		"res://Weapons/Melee/tribal_spear/tribal_spear.tscn"
	],
	"levels": {
		"1": {
			"overwrite_start_rooms": [
				"res://Rooms/Biomes/forest/Start/ForestSpawnRoom0.tscn",
				"res://Rooms/Biomes/forest/Start/forest_spawn_room_2.tscn"
			],
			"overwrite_end_forest_rooms": [
				"res://Rooms/Biomes/forest/End/Forest/ForestEndRoom1.tscn"
			],
			"overwrite_end_sewer_rooms": []
		},
		"2": {
			"spawn_shape_type": "rectangle",
			"spawn_shape_width": 200,
			"spawn_shape_height": 400,
			"disable_horizontal_separation_steering": true,
			"num_combat_rooms": 1,
			"num_chest_rooms": 0,
			"num_special_rooms": 0,
			"overwrite_start_rooms": [
				"res://Rooms/Biomes/forest/Start/ForestSpawnRoom2.tscn"
			],
			"overwrite_combat_rooms": [
				"res://Rooms/Biomes/forest/BossFightRoom.tscn"
			],
			"overwrite_end_forest_rooms": [],
			"overwrite_end_sewer_rooms": [
				"res://Rooms/Biomes/forest/End/Sewer/forest_to_sewer_end_room.tscn"
			],
			"overwrite_connections": [
				[
					0,
					2
				],
				[
					2,
					1
				]
			]
		}
	},
	"music": "res://Audio/Music/Incompetech/Shamanistic.mp3",
	"music_volume_db": -4.0,
	"encyclopedia_background": "res://Rooms/Biomes/forest/forest_background.png"
}
